
      // 
      // Javascript generated by HTML2 Toolkit plugin
      // 
      var tree;
      
      function treeInit() {
      tree = new YAHOO.widget.TreeView("treeDiv1");
      var root = tree.getRoot();

      
var objd67e104 = {
  label: "Part I.  Getting Started",
  href: "GettingStarted.html", 
  target:"contentwin"
};
var d67e104 = new YAHOO.widget.TextNode(objd67e104, root, false);

var objd67e156 = {
  label: "Chapter 1.  Introducing The 5D Mark IV",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e156 = new YAHOO.widget.TextNode(objd67e156, d67e104, false);

var objd67e205 = {
  label: " 22.3 Megapixel Full-Frame CMOS Sensor",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e205 = new YAHOO.widget.TextNode(objd67e205, d67e156, false);

var objd67e257 = {
  label: " DIGIC 5+ Image Processor",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e257 = new YAHOO.widget.TextNode(objd67e257, d67e156, false);

var objd67e309 = {
  label: " 61-Point High Density AF",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e309 = new YAHOO.widget.TextNode(objd67e309, d67e156, false);

var objd67e361 = {
  label: " EOS HD Video",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e361 = new YAHOO.widget.TextNode(objd67e361, d67e156, false);

var objd67e413 = {
  label: " Metering Sensor",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e413 = new YAHOO.widget.TextNode(objd67e413, d67e156, false);

var objd67e461 = {
  label: " Intelligent Viewfinder",
  href: "IntroducingThe5DMarkIV.html", 
  target:"contentwin"
};
var d67e461 = new YAHOO.widget.TextNode(objd67e461, d67e156, false);

var objd67e509 = {
  label: "Chapter 2.  Initial Setup",
  href: "InitialSetup.html", 
  target:"contentwin"
};
var d67e509 = new YAHOO.widget.TextNode(objd67e509, d67e104, false);

var objd67e561 = {
  label: " What\'s In the Box",
  href: "What'sInTheBox.html", 
  target:"contentwin"
};
var d67e561 = new YAHOO.widget.TextNode(objd67e561, d67e509, false);

var objd67e613 = {
  label: " 5D Mark IV At a Glance",
  href: "5DMarkIVAtAGlance.html", 
  target:"contentwin"
};
var d67e613 = new YAHOO.widget.TextNode(objd67e613, d67e509, false);

var objd67e661 = {
  label: " Installing Batteries",
  href: "InstallingBatteries.html", 
  target:"contentwin"
};
var d67e661 = new YAHOO.widget.TextNode(objd67e661, d67e509, false);

var objd67e713 = {
  label: "Chapter 3.  Taking Your First Photo",
  href: "TakingYourFirstPhoto.html", 
  target:"contentwin"
};
var d67e713 = new YAHOO.widget.TextNode(objd67e713, d67e104, false);

var objd67e766 = {
  label: " About Your First Photo",
  href: "AboutYourFirstPhoto.html", 
  target:"contentwin"
};
var d67e766 = new YAHOO.widget.TextNode(objd67e766, d67e713, false);

var objd67e818 = {
  label: " Steps for Taking Your First Photo",
  href: "StepsForTakingYourFirstPhoto.html", 
  target:"contentwin"
};
var d67e818 = new YAHOO.widget.TextNode(objd67e818, d67e713, false);

var objd67e870 = {
  label: " Setting Automatic Mode",
  href: "SettingAutomaticMode.html", 
  target:"contentwin"
};
var d67e870 = new YAHOO.widget.TextNode(objd67e870, d67e818, false);

var objd67e922 = {
  label: " Focusing and Shooting",
  href: "FocusingShooting.html", 
  target:"contentwin"
};
var d67e922 = new YAHOO.widget.TextNode(objd67e922, d67e818, false);

var objd67e975 = {
  label: "Part II.  Taking Photos",
  href: "TakingPhotos.html", 
  target:"contentwin"
};
var d67e975 = new YAHOO.widget.TextNode(objd67e975, root, false);

var objd67e1027 = {
  label: "Chapter 4.  Using Automatic Modes",
  href: "UsingAutomaticModes.html", 
  target:"contentwin"
};
var d67e1027 = new YAHOO.widget.TextNode(objd67e1027, d67e975, false);

var objd67e1078 = {
  label: " Using Intelligent Auto Mode",
  href: "UsingQuickAutoMode.html", 
  target:"contentwin"
};
var d67e1078 = new YAHOO.widget.TextNode(objd67e1078, d67e1027, false);

var objd67e1130 = {
  label: " Using Scene Modes",
  href: "UsingSceneModes.html", 
  target:"contentwin"
};
var d67e1130 = new YAHOO.widget.TextNode(objd67e1130, d67e1027, false);

var objd67e1182 = {
  label: " Scene Modes Descriptions",
  href: "SceneModesDescriptions.html", 
  target:"contentwin"
};
var d67e1182 = new YAHOO.widget.TextNode(objd67e1182, d67e1027, false);

var objd67e1233 = {
  label: " Creative Auto Shooting",
  href: "CreativeAutoShooting.html", 
  target:"contentwin"
};
var d67e1233 = new YAHOO.widget.TextNode(objd67e1233, d67e1027, false);

var objd67e1285 = {
  label: "Chapter 5.  Using Flash",
  href: "UsingFlash.html", 
  target:"contentwin"
};
var d67e1285 = new YAHOO.widget.TextNode(objd67e1285, d67e975, false);

var objd67e1337 = {
  label: " About Canon Flash",
  href: "AboutCanonFlash.html", 
  target:"contentwin"
};
var d67e1337 = new YAHOO.widget.TextNode(objd67e1337, d67e1285, false);

var objd67e1350 = {
  label: " Using the Internal Flash",
  href: "UsingTheInternalFlash.html", 
  target:"contentwin"
};
var d67e1350 = new YAHOO.widget.TextNode(objd67e1350, d67e1285, false);

var objd67e1362 = {
  label: " Using External Flash",
  href: "UsingExternalFlash.html", 
  target:"contentwin"
};
var d67e1362 = new YAHOO.widget.TextNode(objd67e1362, d67e1285, false);

var objd67e1374 = {
  label: " Using Multiple Flashes with Wireless",
  href: "UsingMultipleFlashesWithWireless.html", 
  target:"contentwin"
};
var d67e1374 = new YAHOO.widget.TextNode(objd67e1374, d67e1285, false);

var objd67e1386 = {
  label: " About the Canon Wireless Flash System",
  href: "UsingMultipleFlashesWithWireless.html", 
  target:"contentwin"
};
var d67e1386 = new YAHOO.widget.TextNode(objd67e1386, d67e1374, false);

var objd67e1401 = {
  label: " Configuring a Two-Light Setup",
  href: "UsingMultipleFlashesWithWireless.html", 
  target:"contentwin"
};
var d67e1401 = new YAHOO.widget.TextNode(objd67e1401, d67e1374, false);

var objd67e1413 = {
  label: "Chapter 6.  Advanced Features",
  href: "AdvancedFeatures.html", 
  target:"contentwin"
};
var d67e1413 = new YAHOO.widget.TextNode(objd67e1413, d67e975, false);

var objd67e1465 = {
  label: " Shooting RAW vs. JPEG",
  href: "ShootingRAWVs.JPEG.html", 
  target:"contentwin"
};
var d67e1465 = new YAHOO.widget.TextNode(objd67e1465, d67e1413, false);

var objd67e1517 = {
  label: " Understanding Metering Modes",
  href: "UnderstandingMeteringModes.html", 
  target:"contentwin"
};
var d67e1517 = new YAHOO.widget.TextNode(objd67e1517, d67e1413, false);

var objd67e1570 = {
  label: " Appendixes",
  href: "Appendixes.html", 
  target:"contentwin"
};
var d67e1570 = new YAHOO.widget.TextNode(objd67e1570, root, false);

var objd67e1618 = {
  label: " Custom Functions",
  href: "CustomFunctions.html", 
  target:"contentwin"
};
var d67e1618 = new YAHOO.widget.TextNode(objd67e1618, d67e1570, false);

var objd67e1670 = {
  label: " Specifications",
  href: "Specifications.html", 
  target:"contentwin"
};
var d67e1670 = new YAHOO.widget.TextNode(objd67e1670, d67e1570, false);

var objd67e1719 = {
  label: " General Specifications",
  href: "Specifications_General.html", 
  target:"contentwin"
};
var d67e1719 = new YAHOO.widget.TextNode(objd67e1719, d67e1670, false);

var objd67e1767 = {
  label: " Physical Specifications",
  href: "Specifications_Physical.html", 
  target:"contentwin"
};
var d67e1767 = new YAHOO.widget.TextNode(objd67e1767, d67e1670, false);

var objd67e1815 = {
  label: " Canon USB APIs",
  href: "CanonUSBAPIs.html", 
  target:"contentwin"
};
var d67e1815 = new YAHOO.widget.TextNode(objd67e1815, d67e1570, false);

var objd67e1873 = {
  label: " aperture",
  href: "glossary/g_aperture.html", 
  target:"contentwin"
};
var d67e1873 = new YAHOO.widget.TextNode(objd67e1873, root, false);

var objd67e1921 = {
  label: " aperture priority",
  href: "glossary/g_aperture-priority.html", 
  target:"contentwin"
};
var d67e1921 = new YAHOO.widget.TextNode(objd67e1921, root, false);

var objd67e1969 = {
  label: " bracketing",
  href: "glossary/g_bracketing.html", 
  target:"contentwin"
};
var d67e1969 = new YAHOO.widget.TextNode(objd67e1969, root, false);

var objd67e2017 = {
  label: " chromatic aberration",
  href: "glossary/g_chromatic-aberration.html", 
  target:"contentwin"
};
var d67e2017 = new YAHOO.widget.TextNode(objd67e2017, root, false);

var objd67e2065 = {
  label: " depth of field",
  href: "glossary/g_depth-of-field.html", 
  target:"contentwin"
};
var d67e2065 = new YAHOO.widget.TextNode(objd67e2065, root, false);

var objd67e2113 = {
  label: " distortion",
  href: "glossary/g_distortion.html", 
  target:"contentwin"
};
var d67e2113 = new YAHOO.widget.TextNode(objd67e2113, root, false);

var objd67e2161 = {
  label: " EV",
  href: "glossary/g_EV.html", 
  target:"contentwin"
};
var d67e2161 = new YAHOO.widget.TextNode(objd67e2161, root, false);

var objd67e2209 = {
  label: " exposure compensation",
  href: "glossary/g_exposure-compensation.html", 
  target:"contentwin"
};
var d67e2209 = new YAHOO.widget.TextNode(objd67e2209, root, false);

var objd67e2257 = {
  label: " f-stop",
  href: "glossary/g_f-stop.html", 
  target:"contentwin"
};
var d67e2257 = new YAHOO.widget.TextNode(objd67e2257, root, false);

var objd67e2305 = {
  label: " flash sync speed",
  href: "glossary/g_flash-sync-speed.html", 
  target:"contentwin"
};
var d67e2305 = new YAHOO.widget.TextNode(objd67e2305, root, false);

var objd67e2354 = {
  label: " focal length",
  href: "glossary/g_focal-length.html", 
  target:"contentwin"
};
var d67e2354 = new YAHOO.widget.TextNode(objd67e2354, root, false);

var objd67e2402 = {
  label: " hot shoe",
  href: "glossary/g_hot-show.html", 
  target:"contentwin"
};
var d67e2402 = new YAHOO.widget.TextNode(objd67e2402, root, false);

var objd67e2450 = {
  label: " ISO",
  href: "glossary/g_ISO.html", 
  target:"contentwin"
};
var d67e2450 = new YAHOO.widget.TextNode(objd67e2450, root, false);

var objd67e2498 = {
  label: " PC Terminal/PC socket",
  href: "glossary/g_pc-terminal.html", 
  target:"contentwin"
};
var d67e2498 = new YAHOO.widget.TextNode(objd67e2498, root, false);

var objd67e2546 = {
  label: " resolution",
  href: "glossary/g_resolution.html", 
  target:"contentwin"
};
var d67e2546 = new YAHOO.widget.TextNode(objd67e2546, root, false);

var objd67e2594 = {
  label: " sharpness",
  href: "glossary/g_sharpness.html", 
  target:"contentwin"
};
var d67e2594 = new YAHOO.widget.TextNode(objd67e2594, root, false);

var objd67e2642 = {
  label: " shutter priority",
  href: "glossary/g_shutter-priority.html", 
  target:"contentwin"
};
var d67e2642 = new YAHOO.widget.TextNode(objd67e2642, root, false);

var objd67e2690 = {
  label: " slave unit",
  href: "glossary/g_slave-unit.html", 
  target:"contentwin"
};
var d67e2690 = new YAHOO.widget.TextNode(objd67e2690, root, false);

var objd67e2738 = {
  label: " slow sync",
  href: "glossary/g_slow-sync.html", 
  target:"contentwin"
};
var d67e2738 = new YAHOO.widget.TextNode(objd67e2738, root, false);

var objd67e2786 = {
  label: " sync speed",
  href: "glossary/g_sync-speed.html", 
  target:"contentwin"
};
var d67e2786 = new YAHOO.widget.TextNode(objd67e2786, root, false);

var objd67e2834 = {
  label: " telephoto lens",
  href: "glossary/g_telephoto-lens.html", 
  target:"contentwin"
};
var d67e2834 = new YAHOO.widget.TextNode(objd67e2834, root, false);

var objd67e2883 = {
  label: " through-the-lens metering",
  href: "glossary/g_through-the-lens-metering.html", 
  target:"contentwin"
};
var d67e2883 = new YAHOO.widget.TextNode(objd67e2883, root, false);

var objd67e2931 = {
  label: " TTL auto flash",
  href: "glossary/g_TTL-auto-flash.html", 
  target:"contentwin"
};
var d67e2931 = new YAHOO.widget.TextNode(objd67e2931, root, false);

var objd67e2979 = {
  label: " zoom lens",
  href: "glossary/g_zoom-lens.html", 
  target:"contentwin"
};
var d67e2979 = new YAHOO.widget.TextNode(objd67e2979, root, false);
var d129e338 = new YAHOO.widget.TextNode("Index", root, false);
var d129e339 = new YAHOO.widget.TextNode("A", d129e338, false);
var d129e343 = new YAHOO.widget.TextNode("APIs", d129e339, false);

var objd129e350 = {
    label: "[Canon USB APIs]",
    href: "CanonUSBAPIs.html", 
    target:"contentwin"
};
var d129e350 = new YAHOO.widget.TextNode(objd129e350, d129e343, false);
var d129e354 = new YAHOO.widget.TextNode("automatic mode", d129e339, false);

var objd129e361 = {
    label: "[Using Automatic Modes]",
    href: "UsingAutomaticModes.html", 
    target:"contentwin"
};
var d129e361 = new YAHOO.widget.TextNode(objd129e361, d129e354, false);
var d129e365 = new YAHOO.widget.TextNode("Automatic mode", d129e339, false);

var objd129e372 = {
    label: "[Setting Automatic Mode]",
    href: "SettingAutomaticMode.html", 
    target:"contentwin"
};
var d129e372 = new YAHOO.widget.TextNode(objd129e372, d129e365, false);
var d129e376 = new YAHOO.widget.TextNode("B", d129e338, false);
var d129e380 = new YAHOO.widget.TextNode("batteries", d129e376, false);
var d129e389 = new YAHOO.widget.TextNode("installing", d129e380, false);

var objd129e396 = {
    label: "[Installing Batteries]",
    href: "InstallingBatteries.html", 
    target:"contentwin"
};
var d129e396 = new YAHOO.widget.TextNode(objd129e396, d129e389, false);
var d129e400 = new YAHOO.widget.TextNode("box contents", d129e376, false);

var objd129e407 = {
    label: "[What\'s In the Box]",
    href: "What'sInTheBox.html", 
    target:"contentwin"
};
var d129e407 = new YAHOO.widget.TextNode(objd129e407, d129e400, false);
var d129e411 = new YAHOO.widget.TextNode("C", d129e338, false);
var d129e415 = new YAHOO.widget.TextNode("CMOS Sensor", d129e411, false);

var objd129e422 = {
    label: "[22.3 Megapixel Full-Frame CMOS Sensor]",
    href: "IntroducingThe5DMarkIV.html", 
    target:"contentwin"
};
var d129e422 = new YAHOO.widget.TextNode(objd129e422, d129e415, false);
var d129e426 = new YAHOO.widget.TextNode("Creative Auto", d129e411, false);

var objd129e433 = {
    label: "[Creative Auto Shooting]",
    href: "CreativeAutoShooting.html", 
    target:"contentwin"
};
var d129e433 = new YAHOO.widget.TextNode(objd129e433, d129e426, false);
var d129e437 = new YAHOO.widget.TextNode("custom functions.", d129e411, false);

var objd129e444 = {
    label: "[Custom Functions]",
    href: "CustomFunctions.html", 
    target:"contentwin"
};
var d129e444 = new YAHOO.widget.TextNode(objd129e444, d129e437, false);
var d129e448 = new YAHOO.widget.TextNode("E", d129e338, false);
var d129e452 = new YAHOO.widget.TextNode("external flash", d129e448, false);

var objd129e459 = {
    label: "[Using External Flash]",
    href: "UsingExternalFlash.html", 
    target:"contentwin"
};
var d129e459 = new YAHOO.widget.TextNode(objd129e459, d129e452, false);
var d129e463 = new YAHOO.widget.TextNode("F", d129e338, false);
var d129e467 = new YAHOO.widget.TextNode("first photo", d129e463, false);
var d129e476 = new YAHOO.widget.TextNode("about", d129e467, false);

var objd129e483 = {
    label: "[About Your First Photo]",
    href: "AboutYourFirstPhoto.html", 
    target:"contentwin"
};
var d129e483 = new YAHOO.widget.TextNode(objd129e483, d129e476, false);
var d129e487 = new YAHOO.widget.TextNode("flash", d129e463, false);
var d129e496 = new YAHOO.widget.TextNode("wireless", d129e487, false);

var objd129e503 = {
    label: "[Using Multiple Flashes with Wireless]",
    href: "UsingMultipleFlashesWithWireless.html", 
    target:"contentwin"
};
var d129e503 = new YAHOO.widget.TextNode(objd129e503, d129e496, false);
var d129e507 = new YAHOO.widget.TextNode("focusing", d129e463, false);

var objd129e514 = {
    label: "[Focusing and Shooting]",
    href: "FocusingShooting.html", 
    target:"contentwin"
};
var d129e514 = new YAHOO.widget.TextNode(objd129e514, d129e507, false);
var d129e518 = new YAHOO.widget.TextNode("I", d129e338, false);
var d129e522 = new YAHOO.widget.TextNode("installing batteries", d129e518, false);

var objd129e529 = {
    label: "[Installing Batteries]",
    href: "InstallingBatteries.html", 
    target:"contentwin"
};
var d129e529 = new YAHOO.widget.TextNode(objd129e529, d129e522, false);
var d129e533 = new YAHOO.widget.TextNode("intelligent auto", d129e518, false);

var objd129e540 = {
    label: "[Using Intelligent Auto Mode]",
    href: "UsingQuickAutoMode.html", 
    target:"contentwin"
};
var d129e540 = new YAHOO.widget.TextNode(objd129e540, d129e533, false);
var d129e544 = new YAHOO.widget.TextNode("internal flash", d129e518, false);

var objd129e551 = {
    label: "[Using the Internal Flash]",
    href: "UsingTheInternalFlash.html", 
    target:"contentwin"
};
var d129e551 = new YAHOO.widget.TextNode(objd129e551, d129e544, false);
var d129e555 = new YAHOO.widget.TextNode("J", d129e338, false);
var d129e559 = new YAHOO.widget.TextNode("JPEG", d129e555, false);

var objd129e566 = {
    label: "[Advanced Features]",
    href: "AdvancedFeatures.html", 
    target:"contentwin"
};
var d129e566 = new YAHOO.widget.TextNode(objd129e566, d129e559, false);
var d129e570 = new YAHOO.widget.TextNode("JPEG\nquality", d129e555, false);

var objd129e577 = {
    label: "[Shooting RAW vs. JPEG]",
    href: "ShootingRAWVs.JPEG.html", 
    target:"contentwin"
};
var d129e577 = new YAHOO.widget.TextNode(objd129e577, d129e570, false);
var d129e581 = new YAHOO.widget.TextNode("M", d129e338, false);
var d129e585 = new YAHOO.widget.TextNode("metering", d129e581, false);

var objd129e592 = {
    label: "[Understanding Metering Modes]",
    href: "UnderstandingMeteringModes.html", 
    target:"contentwin"
};
var d129e592 = new YAHOO.widget.TextNode(objd129e592, d129e585, false);
var d129e596 = new YAHOO.widget.TextNode("modes, scene", d129e581, false);

var objd129e603 = {
    label: "[Using Automatic Modes]",
    href: "UsingAutomaticModes.html", 
    target:"contentwin"
};
var d129e603 = new YAHOO.widget.TextNode(objd129e603, d129e596, false);
var d129e607 = new YAHOO.widget.TextNode("modes,\nscene", d129e581, false);

var objd129e614 = {
    label: "[Using Scene Modes]",
    href: "UsingSceneModes.html", 
    target:"contentwin"
};
var d129e614 = new YAHOO.widget.TextNode(objd129e614, d129e607, false);
var d129e618 = new YAHOO.widget.TextNode("P", d129e338, false);
var d129e622 = new YAHOO.widget.TextNode("processor", d129e618, false);

var objd129e629 = {
    label: "[DIGIC 5+ Image Processor]",
    href: "IntroducingThe5DMarkIV.html", 
    target:"contentwin"
};
var d129e629 = new YAHOO.widget.TextNode(objd129e629, d129e622, false);
var d129e633 = new YAHOO.widget.TextNode("R", d129e338, false);
var d129e637 = new YAHOO.widget.TextNode("RAW files", d129e633, false);

var objd129e644 = {
    label: "[Advanced Features]",
    href: "AdvancedFeatures.html", 
    target:"contentwin"
};
var d129e644 = new YAHOO.widget.TextNode(objd129e644, d129e637, false);

var objd129e647 = {
    label: "[Shooting RAW vs. JPEG]",
    href: "ShootingRAWVs.JPEG.html", 
    target:"contentwin"
};
var d129e647 = new YAHOO.widget.TextNode(objd129e647, d129e637, false);
var d129e651 = new YAHOO.widget.TextNode("S", d129e338, false);
var d129e655 = new YAHOO.widget.TextNode("scene modes", d129e651, false);

var objd129e662 = {
    label: "[Using Automatic Modes]",
    href: "UsingAutomaticModes.html", 
    target:"contentwin"
};
var d129e662 = new YAHOO.widget.TextNode(objd129e662, d129e655, false);

var objd129e665 = {
    label: "[Using Scene Modes]",
    href: "UsingSceneModes.html", 
    target:"contentwin"
};
var d129e665 = new YAHOO.widget.TextNode(objd129e665, d129e655, false);
var d129e669 = new YAHOO.widget.TextNode("shooting", d129e651, false);

var objd129e676 = {
    label: "[Focusing and Shooting]",
    href: "FocusingShooting.html", 
    target:"contentwin"
};
var d129e676 = new YAHOO.widget.TextNode(objd129e676, d129e669, false);
var d129e681 = new YAHOO.widget.TextNode("T", d129e338, false);
var d129e685 = new YAHOO.widget.TextNode("two-light setup", d129e681, false);

var objd129e692 = {
    label: "[Configuring a Two-Light Setup]",
    href: "UsingMultipleFlashesWithWireless.html", 
    target:"contentwin"
};
var d129e692 = new YAHOO.widget.TextNode(objd129e692, d129e685, false);
var d129e696 = new YAHOO.widget.TextNode("W", d129e338, false);
var d129e700 = new YAHOO.widget.TextNode("wireless flash", d129e696, false);

var objd129e707 = {
    label: "[Using Multiple Flashes with Wireless]",
    href: "UsingMultipleFlashesWithWireless.html", 
    target:"contentwin"
};
var d129e707 = new YAHOO.widget.TextNode(objd129e707, d129e700, false);

      
      tree.draw(); 
      } 
      
      YAHOO.util.Event.addListener(window, "load", treeInit);       
    