<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns:local="urn:local-functions"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:rsiwp="http://reallysi.com/namespaces/generic-wordprocessing-xml"
      xmlns:stylemap="http://reallysi.com/namespaces/style-to-tag-map"
      
      exclude-result-prefixes="xs rsiwp stylemap local xsi"
      version="2.0">

  <!--==========================================
    Word DOCX XML to Tech Doc Map and Topics Template Shell XSLT
    
    Copyright (c) 2010 DITA For Publishers 

    Transforms a DOCX document.xml file into a map and topics.
    
    Use this file as the starting point for transforms for specific
    Word document types.
    
    The input to this transform is the document.xml file within a DOCX
    package.
    
    This XSLT is just a shell that configures the output and provides
    a place to integrate additional custom XSLT.
    
    No additional code is required if the style-to-tag mapping can be
    defined via the declarative style to tag mapping document.
    
    =========================================== -->
  
  <!-- Update this reference to reflect where your transform is
       relative to the base code.
    -->
  <xsl:import href="../../xslt/word2dita/docx2dita.xsl"/>
  
  <!-- XSLT Output setting for the default output (that is, the 
       root thing generated by the transform, either the root
       map or the root topic, depending on how the style-to-tag
       mapping is configured.
    -->
  <xsl:output 
    doctype-public="urn:pubid:example.org:doctypes:dita:map"
    doctype-system="map.dtd"
    indent="yes"/>
  
</xsl:stylesheet>